version: '3.9'

services:
  api-service:
    container_name: api-service
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - REDIS_HOSTe=redis
      - POSTGRES_DATABASE_HOST=postgres
      - POSTGRES_DATABASE_PASSWORD=postgres
    ports:
      - 3000:${APP_PORT}
    depends_on:
      - postgres
      - redis
    restart: on-failure

  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data/redis
volumes:
  pg_data:
  redis_data:
